spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/vedmichv/eks-blueprints-workloads.git
    targetRevision: main
  ingress:
    host: dev.example.com